openapi: 3.0.0
info:
    title: Services API
    version: 1.0.0
servers:
    - url: https://rest.websupport.sk/v1
components:
    securitySchemes:
        basicAuth:
            type: http
            scheme: basic
paths:
    # Service management
    /user/{userId}/service:
        get:
            summary: List of all services
            description: Retrieves information about all services.
            tags:
                - Service management
            parameters:
                - name: userId
                  in: path
                  required: true
                  schema:
                      type: string
                      description: User ID or "self" for currently logged user
                - name: date
                  in: header
                  description: The time used for the signature in the ISO8601 basic format, in the GMT timezone.
                  required: true
                  schema:
                      type: string
                      format: date-time
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    items:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                id:
                                                    type: integer
                                                serviceName:
                                                    type: string
                                                status:
                                                    type: string
                                                name:
                                                    type: string
                                                createTime:
                                                    type: integer
                                                expireTime:
                                                    type: integer
                                                price:
                                                    type: number
                                                autoExtend:
                                                    type: boolean
                                    pager:
                                        type: object
                                        properties:
                                            page:
                                                type: integer
                                            pagesize:
                                                type: integer
                                            items:
                                                type: integer
                "401":
                    description: Unauthorized
                "403":
                    description: Forbidden
    /user/{userId}/service/{serviceId}:
        get:
            summary: Get a service detail
            description: Retrieves detailed information about a specific service.
            tags:
                - Service management
            parameters:
                - name: userId
                  in: path
                  required: true
                  schema:
                      type: string
                      description: User ID or "self" for currently logged user
                - name: serviceId
                  in: path
                  required: true
                  schema:
                      type: integer
                      description: Service ID
                - name: date
                  in: header
                  description: The time used for the signature in the ISO8601 basic format, in the GMT timezone.
                  required: true
                  schema:
                      type: string
                      format: date-time
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                    serviceName:
                                        type: string
                                    status:
                                        type: string
                                    name:
                                        type: string
                                    createTime:
                                        type: integer
                                    expireTime:
                                        type: integer
                                    price:
                                        type: number
                                    autoExtend:
                                        type: boolean
                "401":
                    description: Unauthorized
                "403":
                    description: Forbidden
                "404":
                    description: Not Found
        put:
            summary: Update service
            description: Updates the settings of a specific service.
            tags:
                - Service management
            parameters:
                - name: userId
                  in: path
                  required: true
                  schema:
                      type: string
                      description: User ID or "self" for currently logged user
                - name: serviceId
                  in: path
                  required: true
                  schema:
                      type: integer
                      description: Service ID
                - name: date
                  in: header
                  description: The time used for the signature in the ISO8601 basic format, in the GMT timezone.
                  required: true
                  schema:
                      type: string
                      format: date-time
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                autoExtend:
                                    type: boolean
                                    description: Whether to automatically pay service from credits before expiration
            responses:
                "201":
                    description: Success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: string
                                    item:
                                        type: object
                                        properties:
                                            id:
                                                type: integer
                                            serviceName:
                                                type: string
                                            status:
                                                type: string
                                            name:
                                                type: string
                                            createTime:
                                                type: integer
                                            expireTime:
                                                type: integer
                                            price:
                                                type: number
                                            autoExtend:
                                                type: boolean
                                    errors:
                                        type: object
                "401":
                    description: Unauthorized
                "403":
                    description: Forbidden
                "404":
                    description: Not Found
